name: Build Python Wheel and Release

on:
  push:
    tags:
      - 'v*'   # Trigger on tags which contain versions, starting with 'v'

jobs:
  build:
    runs-on: ubuntu-latest
    environment: protree-whl
    permissions: write-all


    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install build dependencies
        run: |
          python -m pip install --upgrade pip
          pip install wheel setuptools

      - name: Set package version from tag
        run: |
          TAG=$(echo "${GITHUB_REF#refs/tags/}")
          sed -i "s/version=.*/version='$TAG',/" ./setup.py
        shell: bash

      - name: Build wheel
        run: |
          python setup.py sdist bdist_wheel

      - name: Create GitHub Release
        uses: actions/create-release@v1
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_GITHUB }}

      - name: Upload to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}
